version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gomatch-mysql
    environment:
      MYSQL_ROOT_PASSWORD: gomatch123
      MYSQL_DATABASE: gomatch
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: gomatch-redis
    ports:
      - "6379:6379"

volumes:
  mysql-data:
